### ISSUE TITLE
服务端长时间待机失效

### ISSUE THREAD

**Issue by StephanoGeorge** [CJieLuo/NotificationPush#4]
若服务端长时间（如一两天）待机（不操作设备），服务端会失效
设备并没有休眠，因为每次QQ消息接收（状态栏通知）得都及时
不操作设备前，在此应用前台锁屏，两天后解锁即在桌面，重新打开此应用所需的时间与强行停止后打开所需的时间大致相同
使其重新生效的操作为：重启通知监听服务
排除系统问题：开启Tasker通知监听器并测试，两天后其仍在正常运行
服务端：红米 NOTE 1LTE TD，Mokee 71.2-dior-190228-HISTORY，Android 7.1.2

**Comment by RichardLuo0** [comment]
确定fq软件没掉线吗？

**Comment by StephanoGeorge** [comment]
> 确定fq软件没掉线吗？

确定没有，因为只需重启通知监听服务，即可使其重新生效

**Comment by RichardLuo0** [comment]
> > 确定fq软件没掉线吗？
> 
> 确定没有，因为只需重启通知监听服务，即可使其重新生效

你试试GIthub上的1.1.1(1)版本

**Comment by StephanoGeorge** [comment]
> > > 确定fq软件没掉线吗？
> > 
> > 
> > 确定没有，因为只需重启通知监听服务，即可使其重新生效
> 
> 你试试GIthub上的1.1.1(1)版本

OK，我来测试两天

**Comment by StephanoGeorge** [comment]
这些天飞机被封杀了，今天使用特别的方法使服务端突破了墙，测试发现数天未动的服务端依旧可以正常运行，bug解决了
