### ISSUE TITLE
能否弄一个在Linux服务器上运行的

### ISSUE THREAD

**Issue by Kvinam** [CJieLuo/NotificationPush#5]
rt

**Comment by RichardLuo0** [comment]
你是希望能转发linux的通知还是要把通知转发到linux？

**Comment by CAB233** [comment]
> 你是希望能转发linux的通知还是要把通知转发到linux？

就是在云服务器上部署fcm转发，就不需要备用机了

**Comment by RichardLuo0** [comment]
> > 你是希望能转发linux的通知还是要把通知转发到linux？
> 
> 就是在云服务器上部署fcm转发，就不需要备用机了

你可以试试在云服务器上跑个 [anbox](https://github.com/anbox/anbox) ，然后在里面装qq和fcm通知转发。
如果你想转发的是linux的桌面通知，那可能还有办法，但是比如qq一类他用了自己的通知系统，就没办法了。
