### ISSUE TITLE
同步好友QQ头像数据库失败

### ISSUE THREAD

**Issue by 12skoko** [CJieLuo/NotificationPush#6]
网页已经登录，群组的头像可以正常同步，但是同步好友就显示解析错误

**Comment by RichardLuo0** [comment]
打开logcat截图看看啥错

**Comment by 12skoko** [comment]
--------- beginning of main
02-22 21:44:43.537 30642 30642 E otificationpus: Not starting debugger since process cannot load the jdwp agent.
02-22 21:44:43.646 30642 30697 E Perf    : Fail to get file list com.RichardLuo.notificationpush
02-22 21:44:43.646 30642 30697 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
02-22 21:44:43.646 30642 30697 E Perf    : Fail to get file list com.RichardLuo.notificationpush
02-22 21:44:43.646 30642 30697 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
02-22 21:44:43.646 30642 30697 E Perf    : Fail to get file list oat
02-22 21:44:43.646 30642 30697 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
02-22 21:44:43.648 30642 30642 E Parcel  : Reading a NULL string not supported here.
02-22 21:44:43.654 30642 30642 E Parcel  : Reading a NULL string not supported here.
02-22 21:44:43.655 30642 30642 E Parcel  : Reading a NULL string not supported here.
02-22 21:44:43.669 30642 30642 E Parcel  : Reading a NULL string not supported here.
--------- beginning of system
02-22 21:45:12.302 30642 30805 E chromium: [ERROR:simple_index_file_posix.cc(36)] opendir /data/user/0/com.RichardLuo.notificationpush/cache/WebView/Default/HTTP Cache/Code Cache/js: No such file or directory (2)
02-22 21:45:12.302 30642 30805 E chromium: [ERROR:simple_index_file.cc(575)] Could not reconstruct index from disk

**Comment by 12skoko** [comment]
21:45的那两条

**Comment by RichardLuo0** [comment]
这两条跟好友头像没啥关系。。

**Comment by 12skoko** [comment]
我同步好友头像后就多出来两条这东西

**Comment by RichardLuo0** [comment]
你要不过几个小时再试，指不定是被腾讯当机器人处理拦截了

**Comment by 12skoko** [comment]
好几天一直是这样，一次也没成功过_(:з」∠)_

**Comment by RichardLuo0** [comment]
你装[这个版本](https://1drv.ms/u/s!AvQ5Yi4H3cH9h6xZJfUFJi_8r2A7Jg?e=DnbLUY)，如果还是解析错误再发下logcat

**Comment by 12skoko** [comment]
ok，我明天试一下

**Comment by 12skoko** [comment]
仍然解析错误，logcat里面是空的QAQ
[录屏](https://gitee.com/otskoko/ihs/raw/master/test/1.mp4)

**Comment by RichardLuo0** [comment]
不好意思，你再试试[这个版本](https://1drv.ms/u/s!AvQ5Yi4H3cH9h6xbpX8gzVfX8HPjcQ?e=2bkVcR)

**Comment by 12skoko** [comment]
--------- beginning of system
--------- beginning of main
02-23 17:34:27.830 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:30.917 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:33.991 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:36.920 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:39.921 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:42.975 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:45.943 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:48.750 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:51.907 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:54.841 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:58.034 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:34:58.533 31150 31150 E chromium: [ERROR:page_load_metrics_update_dispatcher.cc(170)] Invalid first_paint 0.519 s for first_image_paint 0.477 s
02-23 17:35:02.503 31150  8483 E NotificationPush: No value for 0
02-23 17:35:02.503 31150  8483 E NotificationPush: org.json.JSONException: No value for 0
02-23 17:35:02.503 31150  8483 E NotificationPush: 	at org.json.JSONObject.get(JSONObject.java:399)
02-23 17:35:02.503 31150  8483 E NotificationPush: 	at org.json.JSONObject.getJSONObject(JSONObject.java:619)
02-23 17:35:02.503 31150  8483 E NotificationPush: 	at com.RichardLuo.notificationpush.Preferences$9.run(Preferences.java:300)

**Comment by RichardLuo0** [comment]
你试试[这个版本](https://1drv.ms/u/s!AvQ5Yi4H3cH9h6xcFg_LIcF7c1idVw?e=LPmMM6)

**Comment by 12skoko** [comment]
可以了，谢谢！

**Comment by 12skoko** [comment]
好奇怪，有些头像可以显示，有些就不行。
![Uploading Screenshot_20220223-231729__01.jpg…]()

**Comment by 12skoko** [comment]
--------- beginning of system
--------- beginning of crash
02-23 23:08:36.283 31282 31371 E AndroidRuntime: FATAL EXCEPTION: Firebase-Messaging-Intent-Handle
02-23 23:08:36.283 31282 31371 E AndroidRuntime: Process: com.RichardLuo.notificationpush, PID: 31282
02-23 23:08:36.283 31282 31371 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at com.RichardLuo.notificationpush.FCMReceiver.f(:8)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at com.google.firebase.messaging.FirebaseMessagingService.c(Unknown Source:41)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at z1.m3.run(:152)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at f1.t.run(:12)
02-23 23:08:36.283 31282 31371 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
--------- beginning of main

**Comment by 12skoko** [comment]
![](https://user-images.githubusercontent.com/56678322/155349749-48d56a4c-469a-4e5c-b9d1-ce0b99ebe8fe.jpg)

**Comment by RichardLuo0** [comment]
可能是qq接口的问题，你可以到 https://qun.qq.com/member.html 随便一个群点添加成员看看他们的昵称是否是完整的，他有些昵称会返回的不完整导致我匹配不到

**Comment by 12skoko** [comment]
喔喔确实是这样，昵称太长了显示不全了

**Comment by 12skoko** [comment]
谢谢！

**Comment by RichardLuo0** [comment]
没事
